/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DATABASE_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DDF-Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DDF-Vpc": {
      "type": "sst.aws.Vpc"
    }
    "DDF-Website": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}